apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-db
  name: user-db
  namespace: crepestrips
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
  selector:
    app: user-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-db
  name: order-db
  namespace: crepestrips
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
  selector:
    app: order-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-db
  name: admin-db
  namespace: crepestrips
spec:
  clusterIP: None
  ports:
  - name: postgres
    port: 5432
  selector:
    app: admin-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: restaurant-db
  name: restaurant-db
  namespace: crepestrips
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
  selector:
    app: restaurant-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fooditem-db
  name: fooditem-db
  namespace: crepestrips
spec:
  clusterIP: None
  ports:
  - name: mongodb
    port: 27017
  selector:
    app: fooditem-db
