version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  fooditemservice:
    build: ./FoodItemService
    container_name: fooditemservice
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/fooditemdb
      SPRING_RABBITMQ_HOST:    rabbitmq
      SPRING_RABBITMQ_PORT:    5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

  restaurantservice:
    build: ./RestaurantService
    container_name: restaurantservice
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/restaurantdb
      SPRING_RABBITMQ_HOST:    rabbitmq
      SPRING_RABBITMQ_PORT:    5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

volumes:
  mongo_data:
