apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admin-db
  namespace: crepestrips
spec:
  selector:
    matchLabels:
      app: admin-db
  serviceName: admin-db
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-db
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
