apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: crepestrips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: zeyadtarek17/adminservice:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: SPRING_DATA_MONGODB_USERNAME
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: SPRING_DATA_MONGODB_PASSWORD
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: SPRING_RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: SPRING_RABBITMQ_PASSWORD
