server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # We are manually defining routes
      routes:
        - id: user-service
          uri: http://userservice:8081
          predicates:
            - Path=/user/**

        - id: admin-service
          uri: http://adminservice:8080
          predicates:
            - Path=/admin/**

        - id: restaurant-service
          uri: http://restaurantservice:8083
          predicates:
            - Path=/restaurants/**

        - id: fooditem-service
          uri: http://fooditemservice:8082
          predicates:
            - Path=/fooditems/**

        - id: order-service
          uri: http://orderservice:8084
          predicates:
            - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
