server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://userservice:8081
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: admin-service
          uri: http://adminservice:8080
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=1

        - id: restaurant-service
          uri: http://restaurantservice:8083
          predicates:
            - Path=/api/restaurants/**
          filters:
            - StripPrefix=1

        - id: restaurant-service-categories
          uri: http://restaurantservice:8083
          predicates:
            - Path=/api/categories/**
          filters:
            - StripPrefix=1

        - id: fooditem-service
          uri: http://fooditemservice:8082
          predicates:
            - Path=/api/fooditems/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://orderservice:8084
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1