spring:
  application:
    name: admin-service

  data:
    mongodb:
      host: mongodb       # << Use service name, not localhost!
      port: 27017
      database: admindb

  rabbitmq:
    host: rabbitmq        # << Use service name
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: adham.elsegeeny@gmail.com
    password: btcfjymflovnskjy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080

feign:
  client:
    config:
      food-item-service:
        url: http://fooditem-service:8082
      default:
        connect-timeout: 5000
        read-timeout: 60000
