spring:
  application:
    name: admin-service

  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: admindb


  rabbitmq:
    host:     localhost
    port:     5672
    username: guest
    password: guest

server:
  port: 8080
