apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: mostafaahmedd2/user-service:1.0
          ports:
            - containerPort: 8081  # Replace with UserService's port
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/userservice"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"