apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurant-config
  namespace: crepestrips
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://restaurant-db:5432/restaurantservice
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_REDIS_HOST: redis
  SPRING_REDIS_PORT: "6379"
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: guest
