apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-deployment
  namespace: crepestrips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: zeyadtarek17/restaurantservice:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: restaurant-db
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: restaurantservice
            - name: SPRING_DATA_MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: SPRING_DATA_MONGODB_USERNAME
            - name: SPRING_DATA_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: SPRING_DATA_MONGODB_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: SPRING_RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secret
                  key: SPRING_RABBITMQ_PASSWORD
