apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
  namespace: crepestrips
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
