apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: api-gateway
          image: mostafaahmedd2/apigateway:1.0
          ports:
            - containerPort: 8088  # API Gateway port
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"