spring:
  application:
    name: restaurantservice

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: restaurantdb

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8083
