spring:
  application:
    name: restaurant-service

  data:
    mongodb:
      host: mongodb         # << Use the K8s service name
      port: 27017
      database: restaurantdb

  rabbitmq:
    host: rabbitmq          # << Use the K8s service name
    port: 5672
    username: guest
    password: guest

server:
  port: 8083
