apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: mostafaahmedd2/restaurant-service:1.0
          ports:
            - containerPort: 8083  # Replace with RestaurantService's port
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/restaurantdb"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"