version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: order-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - order-network

networks:
  order-network:
    driver: bridge

volumes:
  postgres_data: