apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminservice
  template:
    metadata:
      labels:
        app: adminservice
    spec:
      containers:
      - name: adminservice
        image: zeyadtarek17/adminservice
        ports:
        - containerPort: 8080
        env:
          # Override MongoDB host and port
          - name: SPRING_DATA_MONGODB_HOST
            value: "mongodb"
          - name: SPRING_DATA_MONGODB_PORT
            value: "27017"
          - name: SPRING_DATA_MONGODB_DATABASE
            value: "admindb"
          - name: SPRING_DATA_MONGODB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_ROOT_USERNAME

          - name: SPRING_DATA_MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: MONGO_INITDB_ROOT_PASSWORD

          # Override RabbitMQ host and port
          - name: SPRING_RABBITMQ_HOST
            value: "rabbitmq"
          - name: SPRING_RABBITMQ_PORT
            value: "5672"
