apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: crepestrips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: <your-dockerhub>/adminservice:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: admin-config
        - secretRef:
            name: admin-secret
