apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: crepestrips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: zeyadtarek17/eurekaserver:latest
        ports:
        - containerPort: 8761
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

