apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: crepestrips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: <your-dockerhub>/eurekaserver:latest
        ports:
        - containerPort: 8761
