apiVersion: apps/v1
kind: Deployment
metadata:
  name: fooditem-deployment
  namespace: crepestrips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fooditem-service
  template:
    metadata:
      labels:
        app: fooditem-service
    spec:
      containers:
      - name: fooditem-service
        image: <your-dockerhub>/fooditemservice:latest
        ports:
        - containerPort: 8082
        envFrom:
        - configMapRef:
            name: fooditem-config
        - secretRef:
            name: fooditem-secret
