apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: crepestrips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: <your-dockerhub>/orderservice:latest
        ports:
        - containerPort: 8084
        envFrom:
        - configMapRef:
            name: order-config
        - secretRef:
            name: order-secret
