apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantservice
  template:
    metadata:
      labels:
        app: restaurantservice
    spec:
      containers:
      - name: restaurantservice
        image: zeyadtarek17/restaurantservice
        ports:
        - containerPort: 8080
        env:
          # Override MongoDB host and port
          - name: SPRING_DATA_MONGODB_HOST
            value: "mongodb"
          - name: SPRING_DATA_MONGODB_PORT
            value: "27017"

          # Override RabbitMQ host and port
          - name: SPRING_RABBITMQ_HOST
            value: "rabbitmq"
          - name: SPRING_RABBITMQ_PORT
            value: "5672"
