apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: crepestrips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: omaradell88/user-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: SPRING_DATA_MONGODB_URI
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: admin-config
                  key: SPRING_RABBITMQ_HOST
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-db-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-db-secret
                  key: password