version: '3.8'

services:
  admin-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - backend

  mongo-express:
    image: mongo-express:1.0
    restart: always
    ports:
      - "9000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/?authSource=admin
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - backend

networks:
  backend:
