apiVersion: v1
kind: Secret
metadata:
  name: fooditem-secret
  namespace: crepestrips
type: Opaque
data:
  SPRING_DATA_MONGODB_USERNAME: cm9vdA==         # root
  SPRING_DATA_MONGODB_PASSWORD: cm9vdA==         # root
  SPRING_RABBITMQ_USERNAME: Z3Vlc3Q=             # guest
  SPRING_RABBITMQ_PASSWORD: Z3Vlc3Q=             # guest
