apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: crepestrips
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=
  SPRING_RABBITMQ_PASSWORD: Z3Vlc3Q=
  SPRING_RABBITMQ_USERNAME: Z3Vlc3Q=
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=
