#version: '3.8'
#
#services:
#  userservice:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    depends_on:
#      - postgres
#      - redis_cache
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5433/userservice
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: root
#      SPRING_DATA_REDIS_HOST: redisCache
#      SPRING_DATA_REDIS_PORT: 6379
#
#
#  postgres:
#    image: postgres:15
#    environment:
#      POSTGRES_DB: userservice
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: root
#    ports:
#      - "5433:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#
#
#  redis_cache:
#    image: redis:latest
#    container_name: redisCache
#    ports:
#      - "6379:6379"
#
#  redisinsight:
#    image: redis/redisinsight:latest
#    container_name: redisInsight
#    ports:
#      - "5540:5540"
#    restart: always
#
#volumes:
#  pgdata:
#
#
