FROM openjdk:25-ea-4-jdk-oraclelinux9

WORKDIR /app

COPY target/restaurant-service-0.0.1-SNAPSHOT.jar restaurant-service-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar","restaurant-service-0.0.1-SNAPSHOT.jar"]