apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: mostafaahmedd2/admin-service:1.0
          ports:
            - containerPort: 8080  # Replace with AdminService's port
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongodb:27017/admindb"
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq"