apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: default
spec:
  type: NodePort
  selector:
    app: apigateway
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30082