
spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      database: fooditemdb
  application:
    name: fooditem-service

server:
  port: 8082
