spring:
  application:
    name: fooditem-service

  data:
    mongodb:
      host: mongodb     # << Use the K8s service name
      port: 27017
      database: fooditemdb
      auto-index-creation: true

  rabbitmq:
    host: rabbitmq      # << Use the K8s service name
    port: 5672
    username: guest
    password: guest

server:
  port: 8082