spring:
  application:
    name: fooditemservice

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: fooditemdb
      auto-index-creation: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8082
