apiVersion: v1
kind: Service
metadata:
  name: admin-db
  namespace: crepestrips
spec:
  ports:
    - port: 5432
  clusterIP: None
  selector:
    app: admin-db

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: admin-db
  namespace: crepestrips
spec:
  serviceName: "admin-db"
  replicas: 1
  selector:
    matchLabels:
      app: admin-db
  template:
    metadata:
      labels:
        app: admin-db
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "adminservice"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: admin-secret
              key: SPRING_DATASOURCE_PASSWORD
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
