apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-user-db
  namespace: default
spec:
  serviceName: "postgres-user-db"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-user-db
  template:
    metadata:
      labels:
        app: postgres-user-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: userservice
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi